/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package odin.view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import odin.bo.*;
import odin.dao.*;
import odin.model.*;

/**
 *
 * @author eike.santiago
 */
public class AdminViewGUI extends javax.swing.JFrame {

    /**
     * Creates new form AdminViewGUI
     */
    public AdminViewGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane5 = new javax.swing.JTabbedPane();
        Painel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        text_cpfUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        text_loginUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        text_senhaUsuario = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        text_nomeUsuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        text_senhaUsuarioConfirmacao = new javax.swing.JPasswordField();
        botao_cadastrarUsuario = new javax.swing.JButton();
        tipo_usuario = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaUsuario = new javax.swing.JTable();
        botao_atualizarTabelaUsuario = new javax.swing.JButton();
        botao_alterarUsuario = new javax.swing.JButton();
        botao_excluirUsuario = new javax.swing.JButton();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cargaHoraria = new javax.swing.JTextField();
        nomeDisciplina = new javax.swing.JTextField();
        botao_cadastrarProfessor = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaDisciplina = new javax.swing.JTable();
        botao_AlterarDisciplina = new javax.swing.JButton();
        botao_atualizarTabelaDisciplina1 = new javax.swing.JButton();
        botao_excluirDisciplina = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        text_nomeTurma = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        botao_vincularDisciplina = new javax.swing.JButton();
        text_vincularCodigoDisciplina = new javax.swing.JTextField();
        text_vincularNomeDisciplina = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaVincularDisciplina = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelaVincularProfessor = new javax.swing.JTable();
        botao_vincularDisciplina1 = new javax.swing.JButton();
        text_vincularNomeProfessor = new javax.swing.JTextField();
        text_vincularCodigoProfessor = new javax.swing.JTextField();
        botao_novaTurma = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabelaTurmas = new javax.swing.JTable();
        botao_excluirTurma = new javax.swing.JButton();
        botao_alterarTurma1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Logado como: Administrador");

        jTabbedPane5.setPreferredSize(new java.awt.Dimension(800, 600));
        jTabbedPane5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane5StateChanged(evt);
            }
        });

        Painel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PainelStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("        CPF: ");

        text_cpfUsuario.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        text_cpfUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_cpfUsuarioActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel3.setText("LOGIN USUÁRIO: ");

        text_loginUsuario.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        text_loginUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_loginUsuarioActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("      SENHA: ");

        text_senhaUsuario.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        text_senhaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_senhaUsuarioActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("       NOME:");

        text_nomeUsuario.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        text_nomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nomeUsuarioActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel6.setText("Confirmar Senha:");

        text_senhaUsuarioConfirmacao.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        text_senhaUsuarioConfirmacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_senhaUsuarioConfirmacaoActionPerformed(evt);
            }
        });

        botao_cadastrarUsuario.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        botao_cadastrarUsuario.setText("CADASTRAR");
        botao_cadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cadastrarUsuarioActionPerformed(evt);
            }
        });

        tipo_usuario.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tipo_usuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aluno", "Professor" }));
        tipo_usuario.setSelectedIndex(-1);
        tipo_usuario.setToolTipText("");
        tipo_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo_usuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tipo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(botao_cadastrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(text_senhaUsuarioConfirmacao, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_senhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_nomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_loginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_cpfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_cpfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_nomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_loginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_senhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(text_senhaUsuarioConfirmacao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_cadastrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        Painel.addTab("Cadastro", jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(800, 600));

        tabelaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CPF", "Login", "Nome", "Senha", "Tipo do Usuario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaUsuario);

        jScrollPane2.setViewportView(jScrollPane1);

        botao_atualizarTabelaUsuario.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        botao_atualizarTabelaUsuario.setText("Atualizar tabela");
        botao_atualizarTabelaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_atualizarTabelaUsuarioActionPerformed(evt);
            }
        });

        botao_alterarUsuario.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        botao_alterarUsuario.setText("Alterar");
        botao_alterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_alterarUsuarioActionPerformed(evt);
            }
        });

        botao_excluirUsuario.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        botao_excluirUsuario.setText("Excluir");
        botao_excluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_excluirUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(botao_atualizarTabelaUsuario)
                .addGap(87, 87, 87)
                .addComponent(botao_alterarUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botao_excluirUsuario)
                .addGap(178, 178, 178))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_atualizarTabelaUsuario)
                    .addComponent(botao_alterarUsuario)
                    .addComponent(botao_excluirUsuario))
                .addGap(84, 84, 84))
        );

        Painel.addTab("Usuários cadastrados", jPanel2);

        jTabbedPane5.addTab("Usuários", Painel);

        jTabbedPane6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane6StateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nome:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel7.setText("Carga Horaria:");

        cargaHoraria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargaHorariaActionPerformed(evt);
            }
        });

        nomeDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeDisciplinaActionPerformed(evt);
            }
        });

        botao_cadastrarProfessor.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        botao_cadastrarProfessor.setText("CADASTRAR");
        botao_cadastrarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cadastrarProfessorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(204, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botao_cadastrarProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(272, 272, 272))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addComponent(botao_cadastrarProfessor)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Cadastro", jPanel3);

        tabelaDisciplina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabelaDisciplina);

        botao_AlterarDisciplina.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        botao_AlterarDisciplina.setText("Alterar");
        botao_AlterarDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_AlterarDisciplinaActionPerformed(evt);
            }
        });

        botao_atualizarTabelaDisciplina1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        botao_atualizarTabelaDisciplina1.setText("Atualizar tabela");
        botao_atualizarTabelaDisciplina1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_atualizarTabelaDisciplina1ActionPerformed(evt);
            }
        });

        botao_excluirDisciplina.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        botao_excluirDisciplina.setText("Excluir");
        botao_excluirDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_excluirDisciplinaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(botao_atualizarTabelaDisciplina1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botao_AlterarDisciplina)
                .addGap(26, 26, 26)
                .addComponent(botao_excluirDisciplina)
                .addContainerGap(262, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_atualizarTabelaDisciplina1)
                    .addComponent(botao_excluirDisciplina)
                    .addComponent(botao_AlterarDisciplina))
                .addGap(0, 86, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Disciplinas cadastradas", jPanel4);

        jTabbedPane5.addTab("Disciplinas", jTabbedPane6);

        text_nomeTurma.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel9.setText("NOME DA TURMA");

        botao_vincularDisciplina.setText("Vincular Disciplina");
        botao_vincularDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_vincularDisciplinaActionPerformed(evt);
            }
        });

        text_vincularCodigoDisciplina.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        text_vincularCodigoDisciplina.setEnabled(false);
        text_vincularCodigoDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_vincularCodigoDisciplinaActionPerformed(evt);
            }
        });

        text_vincularNomeDisciplina.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        text_vincularNomeDisciplina.setEnabled(false);

        tabelaVincularDisciplina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código da disciplina", "Nome da disciplina", "Carga Horária"
            }
        ));
        jScrollPane4.setViewportView(tabelaVincularDisciplina);
        if (tabelaVincularDisciplina.getColumnModel().getColumnCount() > 0) {
            tabelaVincularDisciplina.getColumnModel().getColumn(2).setHeaderValue("Carga Horária");
        }

        tabelaVincularProfessor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código do professor", "Nome"
            }
        ));
        jScrollPane5.setViewportView(tabelaVincularProfessor);

        botao_vincularDisciplina1.setText("Vincular Professor");
        botao_vincularDisciplina1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_vincularDisciplina1ActionPerformed(evt);
            }
        });

        text_vincularNomeProfessor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        text_vincularNomeProfessor.setEnabled(false);

        text_vincularCodigoProfessor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        text_vincularCodigoProfessor.setEnabled(false);

        botao_novaTurma.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        botao_novaTurma.setText("Cadastrar nova turma");
        botao_novaTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_novaTurmaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(text_nomeTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botao_novaTurma)
                .addGap(0, 61, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(text_vincularCodigoDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_vincularNomeDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botao_vincularDisciplina)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(text_vincularCodigoProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_vincularNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botao_vincularDisciplina1)))
                .addGap(35, 35, 35))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(text_nomeTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_novaTurma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(text_vincularCodigoDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(text_vincularNomeDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(botao_vincularDisciplina, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(text_vincularCodigoProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(text_vincularNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(botao_vincularDisciplina1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro", jPanel5);

        tabelaTurmas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tabelaTurmas);

        botao_excluirTurma.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        botao_excluirTurma.setText("Excluir");

        botao_alterarTurma1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        botao_alterarTurma1.setText("Alterar");
        botao_alterarTurma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_alterarTurma1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addComponent(botao_alterarTurma1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(botao_excluirTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_excluirTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_alterarTurma1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 47, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Turmas cadastradas", jPanel6);

        jTabbedPane5.addTab("Turmas", jTabbedPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 820, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 428, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipo_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipo_usuarioActionPerformed

    private void botao_cadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cadastrarUsuarioActionPerformed
        // TODO add your handling code here:
        if (text_cpfUsuario.getText().isEmpty() || text_nomeUsuario.getText().isEmpty() || text_loginUsuario.getText().isEmpty() || text_senhaUsuario.getText().isEmpty() || text_senhaUsuarioConfirmacao.getText().isEmpty() || tipo_usuario.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(Painel, "Preencha todos os campos corretamente!!", "Inane error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (!text_senhaUsuario.getText().equals(text_senhaUsuarioConfirmacao.getText())) {
                JOptionPane.showMessageDialog(Painel, "Senhas diferentes!!", "Inane error", JOptionPane.ERROR_MESSAGE);
            }

            UsuarioBO usuario = new UsuarioBO();
            try {
                usuario.inserirUsuario(text_cpfUsuario.getText(), text_nomeUsuario.getText(), text_loginUsuario.getText(), text_senhaUsuario.getText(), tipo_usuario.getSelectedItem().toString());
                JOptionPane.showMessageDialog(Painel, "USUÁRIO INSERIDO COM SUCESSO!!");
                text_cpfUsuario.setText(null);
                text_nomeUsuario.setText(null);
                text_loginUsuario.setText(null);
                text_senhaUsuario.setText(null);
                text_senhaUsuarioConfirmacao.setText(null);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(Painel, "ERRO:  " + ex.getMessage());
            }

        }
    }//GEN-LAST:event_botao_cadastrarUsuarioActionPerformed

    private void text_senhaUsuarioConfirmacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_senhaUsuarioConfirmacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_senhaUsuarioConfirmacaoActionPerformed

    private void text_nomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nomeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_nomeUsuarioActionPerformed

    private void text_senhaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_senhaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_senhaUsuarioActionPerformed

    private void text_loginUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_loginUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_loginUsuarioActionPerformed

    private void text_cpfUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_cpfUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_cpfUsuarioActionPerformed

    private void PainelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_PainelStateChanged
        // TODO add your handling code here:
        gerarTabelaUsuario();
    }//GEN-LAST:event_PainelStateChanged

    private void botao_excluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_excluirUsuarioActionPerformed
        // TODO add your handling code here:
        int dialogResult = JOptionPane.showConfirmDialog(null, "Deseja excluir usuário?", "Warning", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {

            UsuarioBO usuarioBO = new UsuarioBO();
            int i = tabelaUsuario.getSelectedRow();
            if (i < 0) {
                JOptionPane.showMessageDialog(Painel, "Nenhuma linha selecionada!");
            }
            String excluirPorCPF = tabelaUsuario.getValueAt(i, 0).toString();
            try {
                usuarioBO.excluirUsuario(excluirPorCPF);
                gerarTabelaUsuario();
                JOptionPane.showMessageDialog(Painel, "Usuario deletado com sucesso!");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(Painel, "Erro ao deletar usuario");
                Logger.getLogger(AdminViewGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_botao_excluirUsuarioActionPerformed

    private void botao_atualizarTabelaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_atualizarTabelaUsuarioActionPerformed
        // TODO add your handling code here:
        gerarTabelaUsuario();
    }//GEN-LAST:event_botao_atualizarTabelaUsuarioActionPerformed

    private void botao_alterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_alterarUsuarioActionPerformed
        // TODO add your handling code here:
        AlterarUsuarioGUI alterarGUI = new AlterarUsuarioGUI();
        String[] campos = {"CPF", "Login", "Nome", "Senha"};
        int i = tabelaUsuario.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(Painel, "Nenhuma linha selecionada!");
        }
        Object[] dados = {tabelaUsuario.getValueAt(i, 0), tabelaUsuario.getValueAt(i, 1), tabelaUsuario.getValueAt(i, 2), tabelaUsuario.getValueAt(i, 3)};
        alterarGUI.gerarTabela(campos, dados);
        alterarGUI.setVisible(true);
    }//GEN-LAST:event_botao_alterarUsuarioActionPerformed

    private void botao_cadastrarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cadastrarProfessorActionPerformed
        // TODO add your handling code here:
        DisciplinaBO disciplina = new DisciplinaBO();
        int cargaHorariaConvertida;
        try {
            cargaHorariaConvertida = Integer.parseInt(cargaHoraria.getText());
            try {
                disciplina.cadastrarDisciplina(nomeDisciplina.getText(), cargaHorariaConvertida);
                JOptionPane.showMessageDialog(Painel, "Disciplina cadastrada com sucesso");
                nomeDisciplina.setText(null);
                cargaHoraria.setText(null);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(Painel, "ERRO: " + e.getMessage());
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(Painel, "Digite apenas numeros em Carga Horaria");
        }
    }//GEN-LAST:event_botao_cadastrarProfessorActionPerformed

    private void nomeDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeDisciplinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeDisciplinaActionPerformed

    private void cargaHorariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargaHorariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargaHorariaActionPerformed

    private void botao_AlterarDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_AlterarDisciplinaActionPerformed
        // TODO add your handling code here:
        AlterarDisciplinaGUI alterarDisciplinaGUI = new AlterarDisciplinaGUI();
        String[] campos = {"Código da disciplina", "Nome da disciplina", "Carga horária"};
        int i = tabelaDisciplina.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(Painel, "Nenhuma linha selecionada!");
        }
        Object[] dados = {tabelaDisciplina.getValueAt(i, 0), tabelaDisciplina.getValueAt(i, 1), tabelaDisciplina.getValueAt(i, 2)};
        alterarDisciplinaGUI.gerarTabela(campos, dados);
        alterarDisciplinaGUI.setVisible(true);
        tabelaDisciplina.setModel(gerarModeloTabelaDisciplina());
    }//GEN-LAST:event_botao_AlterarDisciplinaActionPerformed

    private void botao_atualizarTabelaDisciplina1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_atualizarTabelaDisciplina1ActionPerformed
        // TODO add your handling code here:
        tabelaDisciplina.setModel(gerarModeloTabelaDisciplina());
    }//GEN-LAST:event_botao_atualizarTabelaDisciplina1ActionPerformed

    private void botao_excluirDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_excluirDisciplinaActionPerformed
        // TODO add your handling code here:
        int dialogResult = JOptionPane.showConfirmDialog(null, "Você tem certeza disso?", "Warning", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {

            DisciplinaBO disciplinaBO = new DisciplinaBO();
            int i = tabelaDisciplina.getSelectedRow();
            if (i < 0) {
                JOptionPane.showMessageDialog(Painel, "Nenhuma linha selecionada!");
            }
            int codigo = Integer.parseInt(tabelaDisciplina.getValueAt(i, 0).toString());
            try {
                disciplinaBO.excluirDisciplina(codigo);
                tabelaDisciplina.setModel(gerarModeloTabelaDisciplina());
                JOptionPane.showMessageDialog(Painel, "Disciplina deletada com sucesso!");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(Painel, "Erro ao deletar disciplina");
                Logger.getLogger(AdminViewGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_botao_excluirDisciplinaActionPerformed

    private void jTabbedPane6StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane6StateChanged
        // TODO add your handling code here:
        tabelaDisciplina.setModel(gerarModeloTabelaDisciplina());
    }//GEN-LAST:event_jTabbedPane6StateChanged

    private void botao_vincularDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_vincularDisciplinaActionPerformed
        // TODO add your handling code here:
          int i = tabelaVincularDisciplina.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(null, "Nenhuma linha selecionada!");
        }
        text_vincularCodigoDisciplina.setText(tabelaVincularDisciplina.getValueAt(i, 0).toString());
        text_vincularNomeDisciplina.setText(tabelaVincularDisciplina.getValueAt(i, 1).toString());

    }//GEN-LAST:event_botao_vincularDisciplinaActionPerformed

    private void botao_vincularDisciplina1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_vincularDisciplina1ActionPerformed
        // TODO add your handling code here:
        int i = tabelaVincularProfessor.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(null, "Nenhuma linha selecionada!");
        }
        text_vincularCodigoProfessor.setText(tabelaVincularProfessor.getValueAt(i, 0).toString());
        text_vincularNomeProfessor.setText(tabelaVincularProfessor.getValueAt(i, 1).toString());
    }//GEN-LAST:event_botao_vincularDisciplina1ActionPerformed

    private void text_vincularCodigoDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_vincularCodigoDisciplinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_vincularCodigoDisciplinaActionPerformed

    private void botao_novaTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_novaTurmaActionPerformed
        // TODO add your handling code here:
        if (text_nomeTurma.getText().isEmpty() || text_vincularCodigoDisciplina.getText().isEmpty() || text_vincularCodigoProfessor.getText().isEmpty() || text_vincularNomeDisciplina.getText().isEmpty() || text_vincularNomeProfessor.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha os campos corretamente");
        }else {
            UsuarioBO usuarioBO = new UsuarioBO();
            usuarioBO.inserirNovaTurma(text_nomeTurma.getText());
            usuarioBO.vincularProfessorTurma(Integer.parseInt(text_vincularCodigoDisciplina.getText()), Integer.parseInt(text_vincularCodigoProfessor.getText()));
            JOptionPane.showMessageDialog(null, "Turma inserida com sucesso!");
            text_nomeTurma.setText("");
            text_vincularCodigoDisciplina.setText("");
            text_vincularCodigoProfessor.setText("");
            text_vincularNomeDisciplina.setText("");
            text_vincularNomeProfessor.setText("");
        }
    }//GEN-LAST:event_botao_novaTurmaActionPerformed

    private void jTabbedPane5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane5StateChanged
        // TODO add your handling code here:
        tabelaVincularDisciplina.setModel(gerarModeloTabelaDisciplina());
        tabelaVincularProfessor.setModel(gerarModeloTabelaProfessoresNaoVinculados());
        gerarTabelaTurmas();
    }//GEN-LAST:event_jTabbedPane5StateChanged
    public void gerarTabelaTurmas(){
        String[] nomesColunas = {"Código da turma", "Nome da turma","Código da disciplina","Nome da disciplina","Código do professor","Professor"};
        DefaultTableModel model = new DefaultTableModel(null, nomesColunas);
        ArrayList<Turma> dadosRecebidos = new ArrayList();
        UsuarioDAO usuarioDAO = new UsuarioDAO();
        try{
            dadosRecebidos = usuarioDAO.listarTurmas();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Erro ao preencher tabela"+ e.getMessage());
        }
        for (Turma novosDados : dadosRecebidos){
             model.addRow(new Object[]{novosDados.getCodigoTurma(),novosDados.getNomeTurma(),novosDados.getCodigoDisciplina(),novosDados.getNomeDisciplina(),novosDados.getCodigoProfessor(),novosDados.getNomeProfessor()});
        }
        tabelaTurmas.setModel(model);
    }
    private void botao_alterarTurma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_alterarTurma1ActionPerformed
        // TODO add your handling code here:
        int i = tabelaTurmas.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(null, "Nenhuma linha selecionada!");
        }
        
        AlterarTurmaGUI alterarTurmaGUI = new AlterarTurmaGUI();
        alterarTurmaGUI.setVisible(true);
        //alterarTurmaGUI.receberDados(tabelaTurmas.getValueAt(i, i), null, null, null, null, null, null, null);
    }//GEN-LAST:event_botao_alterarTurma1ActionPerformed
    public void setNomeDisciplinaVinculada(String texto) {
        text_vincularNomeDisciplina.setText(texto);
    }

    public void setCodigoDisciplinaVinculada(String codigo) {
        text_vincularCodigoDisciplina.setText(codigo);
    }

    public DefaultTableModel gerarModeloTabelaDisciplina() {
        String[] nomesColunas = {"Código da disciplina", "Nome da disciplina", "Carga horária"};
        DefaultTableModel model = new DefaultTableModel(null, nomesColunas);
        ArrayList<Disciplina> listaDisciplinas = new ArrayList<>();
        DisciplinaBO disciplinaBO = new DisciplinaBO();
        DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel();
        try {
            listaDisciplinas = disciplinaBO.consultarDisciplina();
        } catch (SQLException ex) {
            Logger.getLogger(AdminViewGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (Disciplina novaLista : listaDisciplinas) {
            model.addRow(new Object[]{novaLista.getCodigo(), novaLista.getNomeDisciplina(), novaLista.getCargaHoraria()});
        }
        return model;
    }

    public void gerarTabelaUsuario() {
        String[] nomesColunas = {"CPF", "Login", "Nome", "Senha", "Tipo de Usuario"};
        DefaultTableModel model = new DefaultTableModel(null, nomesColunas);
        ArrayList<Usuario> listaUsuarios = new ArrayList<>();
        UsuarioBO usuarioBO = new UsuarioBO();
        try {
            listaUsuarios = usuarioBO.consultarUsuario();
        } catch (SQLException ex) {
            Logger.getLogger(AdminViewGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (Usuario novaLista : listaUsuarios) {
            model.addRow(new Object[]{novaLista.getCPFUsuario(), novaLista.getLoginUsuario(), novaLista.getNomeUsuario(), novaLista.getSenhaUsuario(), novaLista.getTipoUsuario()});
        }
        tabelaUsuario.setModel(model);
    }

    

    public DefaultTableModel gerarModeloTabelaProfessoresNaoVinculados() {
        String[] nomesColunas = {"Código do professor", "Nome do professor"};
        DefaultTableModel model = new DefaultTableModel(null, nomesColunas);
        ArrayList<Professor> listaProfessores = new ArrayList<>();
        UsuarioBO usuarioBO = new UsuarioBO();
        try {
            listaProfessores = usuarioBO.consultarProfessor();
        } catch (SQLException ex) {
            Logger.getLogger(AdminViewGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (Professor novaLista : listaProfessores) {
                    model.addRow(new Object[]{novaLista.getCodigoProfessor(), novaLista.getNomeUsuario()});
             }
        return model;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminViewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminViewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminViewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminViewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminViewGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Painel;
    private javax.swing.JButton botao_AlterarDisciplina;
    private javax.swing.JButton botao_alterarTurma1;
    private javax.swing.JButton botao_alterarUsuario;
    private javax.swing.JButton botao_atualizarTabelaDisciplina1;
    private javax.swing.JButton botao_atualizarTabelaUsuario;
    private javax.swing.JButton botao_cadastrarProfessor;
    private javax.swing.JButton botao_cadastrarUsuario;
    private javax.swing.JButton botao_excluirDisciplina;
    private javax.swing.JButton botao_excluirTurma;
    private javax.swing.JButton botao_excluirUsuario;
    private javax.swing.JButton botao_novaTurma;
    private javax.swing.JButton botao_vincularDisciplina;
    private javax.swing.JButton botao_vincularDisciplina1;
    private javax.swing.JTextField cargaHoraria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTextField nomeDisciplina;
    private javax.swing.JTable tabelaDisciplina;
    private javax.swing.JTable tabelaTurmas;
    private javax.swing.JTable tabelaUsuario;
    private javax.swing.JTable tabelaVincularDisciplina;
    private javax.swing.JTable tabelaVincularProfessor;
    private javax.swing.JTextField text_cpfUsuario;
    private javax.swing.JTextField text_loginUsuario;
    private javax.swing.JTextField text_nomeTurma;
    private javax.swing.JTextField text_nomeUsuario;
    private javax.swing.JTextField text_senhaUsuario;
    private javax.swing.JTextField text_senhaUsuarioConfirmacao;
    private javax.swing.JTextField text_vincularCodigoDisciplina;
    private javax.swing.JTextField text_vincularCodigoProfessor;
    private javax.swing.JTextField text_vincularNomeDisciplina;
    private javax.swing.JTextField text_vincularNomeProfessor;
    private javax.swing.JComboBox tipo_usuario;
    // End of variables declaration//GEN-END:variables
}
