/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package odin.view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import odin.bo.*;
import odin.dao.*;
import odin.model.*;

/**
 *
 * @author eike.santiago
 */
public class AdminViewGUI extends javax.swing.JFrame {

    /**
     * Creates new form AdminViewGUI
     */
    public AdminViewGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane5 = new javax.swing.JTabbedPane();
        Painel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cpf_usuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        login_usuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        senha_usuario = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        nome_usuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        senha_usuarioConfirmacao = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        tipo_usuario = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaUsuario = new javax.swing.JTable();
        botao_atualizarTabelaUsuario = new javax.swing.JButton();
        botao_alterarUsuario = new javax.swing.JButton();
        botao_excluirUsuario = new javax.swing.JButton();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cargaHoraria = new javax.swing.JTextField();
        nomeDisciplina = new javax.swing.JTextField();
        botao_cadastrarProfessor = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaDisciplina = new javax.swing.JTable();
        botao_AlterarDisciplina = new javax.swing.JButton();
        botao_atualizarTabelaDisciplina1 = new javax.swing.JButton();
        botao_excluirDisciplina = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Logado como: Administrador");

        jTabbedPane5.setPreferredSize(new java.awt.Dimension(800, 600));

        Painel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PainelStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("        CPF: ");

        cpf_usuario.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        cpf_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpf_usuarioActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel3.setText("LOGIN USUÁRIO: ");

        login_usuario.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        login_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_usuarioActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("      SENHA: ");

        senha_usuario.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        senha_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senha_usuarioActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("       NOME:");

        nome_usuario.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        nome_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_usuarioActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel6.setText("Confirmar Senha:");

        senha_usuarioConfirmacao.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        senha_usuarioConfirmacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senha_usuarioConfirmacaoActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jButton1.setText("CADASTRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tipo_usuario.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tipo_usuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aluno", "Professor" }));
        tipo_usuario.setSelectedIndex(-1);
        tipo_usuario.setToolTipText("");
        tipo_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo_usuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tipo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(senha_usuarioConfirmacao, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(senha_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nome_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(login_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senha_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(senha_usuarioConfirmacao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(228, Short.MAX_VALUE))
        );

        Painel.addTab("Cadastro", jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(800, 600));

        tabelaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CPF", "Login", "Nome", "Senha", "Tipo do Usuario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaUsuario);

        jScrollPane2.setViewportView(jScrollPane1);

        botao_atualizarTabelaUsuario.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        botao_atualizarTabelaUsuario.setText("Atualizar tabela");
        botao_atualizarTabelaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_atualizarTabelaUsuarioActionPerformed(evt);
            }
        });

        botao_alterarUsuario.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        botao_alterarUsuario.setText("Alterar");
        botao_alterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_alterarUsuarioActionPerformed(evt);
            }
        });

        botao_excluirUsuario.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        botao_excluirUsuario.setText("Excluir");
        botao_excluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_excluirUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(botao_atualizarTabelaUsuario)
                .addGap(87, 87, 87)
                .addComponent(botao_alterarUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botao_excluirUsuario)
                .addGap(178, 178, 178))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_atualizarTabelaUsuario)
                    .addComponent(botao_alterarUsuario)
                    .addComponent(botao_excluirUsuario))
                .addGap(84, 84, 84))
        );

        Painel.addTab("Usuários cadastrados", jPanel2);

        jTabbedPane5.addTab("Usuário", Painel);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nome:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel7.setText("Carga Horaria:");

        cargaHoraria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargaHorariaActionPerformed(evt);
            }
        });

        nomeDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeDisciplinaActionPerformed(evt);
            }
        });

        botao_cadastrarProfessor.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        botao_cadastrarProfessor.setText("CADASTRAR");
        botao_cadastrarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cadastrarProfessorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(213, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botao_cadastrarProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(272, 272, 272))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addComponent(botao_cadastrarProfessor)
                .addContainerGap(270, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Cadastro", jPanel3);

        tabelaDisciplina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabelaDisciplina);

        botao_AlterarDisciplina.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        botao_AlterarDisciplina.setText("Alterar");
        botao_AlterarDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_AlterarDisciplinaActionPerformed(evt);
            }
        });

        botao_atualizarTabelaDisciplina1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        botao_atualizarTabelaDisciplina1.setText("Atualizar tabela");
        botao_atualizarTabelaDisciplina1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_atualizarTabelaDisciplina1ActionPerformed(evt);
            }
        });

        botao_excluirDisciplina.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        botao_excluirDisciplina.setText("Excluir");
        botao_excluirDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_excluirDisciplinaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(botao_atualizarTabelaDisciplina1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botao_AlterarDisciplina)
                .addGap(26, 26, 26)
                .addComponent(botao_excluirDisciplina)
                .addContainerGap(271, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_atualizarTabelaDisciplina1)
                    .addComponent(botao_excluirDisciplina)
                    .addComponent(botao_AlterarDisciplina))
                .addGap(0, 258, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Disciplinas cadastradas", jPanel4);

        jTabbedPane5.addTab("Disciplina", jTabbedPane6);
        jTabbedPane5.addTab("Curso", jTabbedPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipo_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipo_usuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (cpf_usuario.getText().isEmpty() || nome_usuario.getText().isEmpty() || login_usuario.getText().isEmpty() || senha_usuario.getText().isEmpty() || senha_usuarioConfirmacao.getText().isEmpty() || tipo_usuario.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(Painel, "Preencha todos os campos corretamente!!", "Inane error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (!senha_usuario.getText().equals(senha_usuarioConfirmacao.getText())) {
                JOptionPane.showMessageDialog(Painel, "Senhas diferentes!!", "Inane error", JOptionPane.ERROR_MESSAGE);
            }

            UsuarioBO usuario = new UsuarioBO();
            try {
                usuario.inserirUsuario(cpf_usuario.getText(), nome_usuario.getText(), login_usuario.getText(), senha_usuario.getText(), tipo_usuario.getSelectedItem().toString());
                JOptionPane.showMessageDialog(Painel, "USUÁRIO INSERIDO COM SUCESSO!!");
                cpf_usuario.setText(null);
                nome_usuario.setText(null);
                login_usuario.setText(null);
                senha_usuario.setText(null);
                senha_usuarioConfirmacao.setText(null);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(Painel, "ERRO:  " + ex.getMessage());
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void senha_usuarioConfirmacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senha_usuarioConfirmacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senha_usuarioConfirmacaoActionPerformed

    private void nome_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_usuarioActionPerformed

    private void senha_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senha_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senha_usuarioActionPerformed

    private void login_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_usuarioActionPerformed

    private void cpf_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpf_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpf_usuarioActionPerformed

    private void PainelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_PainelStateChanged
        // TODO add your handling code here:
        gerarTabelaUsuario();
        gerarTabelaDisciplina();
    }//GEN-LAST:event_PainelStateChanged

    private void botao_excluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_excluirUsuarioActionPerformed
        // TODO add your handling code here:
        int dialogResult = JOptionPane.showConfirmDialog(null, "Deseja excluir usuário?", "Warning", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {

            UsuarioBO usuarioBO = new UsuarioBO();
            int i = tabelaUsuario.getSelectedRow();
            if (i < 0) {
                JOptionPane.showMessageDialog(Painel, "Nenhuma linha selecionada!");
            }
            String excluirPorCPF = tabelaUsuario.getValueAt(i, 0).toString();
            try {
                usuarioBO.excluirUsuario(excluirPorCPF);
                gerarTabelaUsuario();
                JOptionPane.showMessageDialog(Painel, "Usuario deletado com sucesso!");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(Painel, "Erro ao deletar usuario");
                Logger.getLogger(AdminViewGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_botao_excluirUsuarioActionPerformed

    private void botao_atualizarTabelaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_atualizarTabelaUsuarioActionPerformed
        // TODO add your handling code here:
        gerarTabelaUsuario();
    }//GEN-LAST:event_botao_atualizarTabelaUsuarioActionPerformed

    private void botao_alterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_alterarUsuarioActionPerformed
        // TODO add your handling code here:
        AlterarUsuarioGUI alterarGUI = new AlterarUsuarioGUI();
        String[] campos = {"CPF", "Login", "Nome", "Senha"};
        int i = tabelaUsuario.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(Painel, "Nenhuma linha selecionada!");
        }
        Object[] dados = {tabelaUsuario.getValueAt(i, 0), tabelaUsuario.getValueAt(i, 1), tabelaUsuario.getValueAt(i, 2), tabelaUsuario.getValueAt(i, 3)};
        alterarGUI.gerarTabela(campos, dados);
        alterarGUI.setVisible(true);
    }//GEN-LAST:event_botao_alterarUsuarioActionPerformed

    private void botao_cadastrarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cadastrarProfessorActionPerformed
        // TODO add your handling code here:
        DisciplinaBO disciplina = new DisciplinaBO();
        int cargaHorariaConvertida;
        try {
            cargaHorariaConvertida = Integer.parseInt(cargaHoraria.getText());
            try {
                disciplina.cadastrarDisciplina(nomeDisciplina.getText(), cargaHorariaConvertida);
                JOptionPane.showMessageDialog(Painel, "Disciplina cadastrada com sucesso");
                nomeDisciplina.setText(null);
                cargaHoraria.setText(null);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(Painel, "ERRO: " + e.getMessage());
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(Painel, "Digite apenas numeros em Carga Horaria");
        }
    }//GEN-LAST:event_botao_cadastrarProfessorActionPerformed

    private void nomeDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeDisciplinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeDisciplinaActionPerformed

    private void cargaHorariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargaHorariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargaHorariaActionPerformed

    private void botao_AlterarDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_AlterarDisciplinaActionPerformed
        // TODO add your handling code here:
         AlterarDisciplinaGUI alterarDisciplinaGUI = new AlterarDisciplinaGUI();
        String[] campos = {"Código da disciplina", "Nome da disciplina", "Carga horária"};
        int i = tabelaDisciplina.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(Painel, "Nenhuma linha selecionada!");
        }
        Object[] dados = {tabelaDisciplina.getValueAt(i, 0), tabelaDisciplina.getValueAt(i, 1), tabelaDisciplina.getValueAt(i, 2)};
        alterarDisciplinaGUI.gerarTabela(campos, dados);
        alterarDisciplinaGUI.setVisible(true);
        gerarTabelaDisciplina();
    }//GEN-LAST:event_botao_AlterarDisciplinaActionPerformed

    private void botao_atualizarTabelaDisciplina1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_atualizarTabelaDisciplina1ActionPerformed
        // TODO add your handling code here:
        gerarTabelaDisciplina();
    }//GEN-LAST:event_botao_atualizarTabelaDisciplina1ActionPerformed

    private void botao_excluirDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_excluirDisciplinaActionPerformed
        // TODO add your handling code here:
        int dialogResult = JOptionPane.showConfirmDialog(null, "Você tem certeza disso?", "Warning", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {

            DisciplinaBO disciplinaBO = new DisciplinaBO();
            int i = tabelaDisciplina.getSelectedRow();
            if (i < 0) {
                JOptionPane.showMessageDialog(Painel, "Nenhuma linha selecionada!");
            }
            int codigo = Integer.parseInt(tabelaDisciplina.getValueAt(i, 0).toString());
            try {
                disciplinaBO.excluirDisciplina(codigo);
                gerarTabelaDisciplina();
                JOptionPane.showMessageDialog(Painel, "Disciplina deletada com sucesso!");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(Painel, "Erro ao deletar disciplina");
                Logger.getLogger(AdminViewGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_botao_excluirDisciplinaActionPerformed
    public void gerarTabelaDisciplina() {
        String[] nomesColunas = {"Código da disciplina", "Nome da disciplina", "Carga horária"};
        DefaultTableModel model = new DefaultTableModel(null, nomesColunas);
        ArrayList<Disciplina> listaDisciplinas = new ArrayList<>();
        DisciplinaBO disciplinaBO = new DisciplinaBO();
        try {
            listaDisciplinas = disciplinaBO.consultarDisciplina();
        } catch (SQLException ex) {
            Logger.getLogger(AdminViewGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (Disciplina novaLista : listaDisciplinas) {
            model.addRow(new Object[]{novaLista.getCodigo(), novaLista.getNomeDisciplina(), novaLista.getCargaHoraria()});
        }
        tabelaDisciplina.setModel(model);
    }

    public void gerarTabelaUsuario() {
        String[] nomesColunas = {"CPF", "Login", "Nome", "Senha", "Tipo de Usuario"};
        DefaultTableModel model = new DefaultTableModel(null, nomesColunas);
        ArrayList<Usuario> listaUsuarios = new ArrayList<>();
        UsuarioBO usuarioBO = new UsuarioBO();
        try {
            listaUsuarios = usuarioBO.consultarUsuario();
        } catch (SQLException ex) {
            Logger.getLogger(AdminViewGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (Usuario novaLista : listaUsuarios) {
            model.addRow(new Object[]{novaLista.getCPFUsuario(), novaLista.getLoginUsuario(), novaLista.getNomeUsuario(), novaLista.getSenhaUsuario(), novaLista.getTipoUsuario()});
        }
        tabelaUsuario.setModel(model);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminViewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminViewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminViewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminViewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminViewGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Painel;
    private javax.swing.JButton botao_AlterarDisciplina;
    private javax.swing.JButton botao_alterarUsuario;
    private javax.swing.JButton botao_atualizarTabelaDisciplina1;
    private javax.swing.JButton botao_atualizarTabelaUsuario;
    private javax.swing.JButton botao_cadastrarProfessor;
    private javax.swing.JButton botao_excluirDisciplina;
    private javax.swing.JButton botao_excluirUsuario;
    private javax.swing.JTextField cargaHoraria;
    private javax.swing.JTextField cpf_usuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTextField login_usuario;
    private javax.swing.JTextField nomeDisciplina;
    private javax.swing.JTextField nome_usuario;
    private javax.swing.JTextField senha_usuario;
    private javax.swing.JTextField senha_usuarioConfirmacao;
    private javax.swing.JTable tabelaDisciplina;
    private javax.swing.JTable tabelaUsuario;
    private javax.swing.JComboBox tipo_usuario;
    // End of variables declaration//GEN-END:variables
}
