/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package odin.view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import odin.bo.DisciplinaBO;
import odin.bo.UsuarioBO;
import odin.dao.*;
import odin.model.Professor;
import odin.model.Usuario;

/**
 *
 * @author Francisco
 */
public class EditarNotasGUI extends javax.swing.JFrame {

    /**
     * Creates new form AlterarDisciplinaGUI
     */
    public EditarNotasGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        recebeNome = new javax.swing.JTextField();
        recebeCodigo = new javax.swing.JTextField();
        recebeNota1 = new javax.swing.JTextField();
        btnSalvarNotas = new javax.swing.JButton();
        botao_cancelarDisciplina = new javax.swing.JButton();
        recebeNotaFinal = new javax.swing.JTextField();
        recebeNota2 = new javax.swing.JTextField();
        recebeFaltas = new javax.swing.JTextField();
        text_codTurma = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alterar disciplina");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Código da turma", "Aluno", "Nota AV1", "Nota AV2", "Média", "Faltas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        recebeNome.setEditable(false);
        recebeNome.setEnabled(false);

        recebeCodigo.setEnabled(false);

        btnSalvarNotas.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnSalvarNotas.setText("Salvar");
        btnSalvarNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarNotasActionPerformed(evt);
            }
        });

        botao_cancelarDisciplina.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        botao_cancelarDisciplina.setText("Cancelar");
        botao_cancelarDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cancelarDisciplinaActionPerformed(evt);
            }
        });

        recebeNotaFinal.setEditable(false);
        recebeNotaFinal.setEnabled(false);
        recebeNotaFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recebeNotaFinalActionPerformed(evt);
            }
        });

        recebeNota2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recebeNota2ActionPerformed(evt);
            }
        });

        recebeFaltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recebeFaltasActionPerformed(evt);
            }
        });

        text_codTurma.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(btnSalvarNotas)
                .addGap(106, 106, 106)
                .addComponent(botao_cancelarDisciplina)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(recebeCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_codTurma, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(recebeNome, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recebeNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recebeNota2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recebeNotaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recebeFaltas, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(102, 102, 102))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recebeCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recebeNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recebeNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recebeNotaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recebeNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recebeFaltas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_codTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarNotas)
                    .addComponent(botao_cancelarDisciplina))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void gerarTabela(String[] campos, Object[] dados) {
        DefaultTableModel model = new DefaultTableModel(null, campos);
        jTable1.setModel(model);
        recebeCodigo.setText(dados[0].toString());
        text_codTurma.setText(dados[1].toString());
        recebeNome.setText(dados[2].toString());
        recebeNota1.setText(dados[3].toString());
        recebeNota2.setText(dados[4].toString());
        recebeNotaFinal.setText(dados[5].toString());
        recebeFaltas.setText(dados[6].toString());
    }
    /* public boolean isVinculado(String nome){
        
     }*/

    

    

    
    private void btnSalvarNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarNotasActionPerformed
        // TODO add your handling code here:
        double notaFinal = 0;
        AlunoDAO alunoDAO = new AlunoDAO();
        int codigoAluno = Integer.parseInt(recebeCodigo.getText());
        int codigoTurma = Integer.parseInt(text_codTurma.getText());
        String nomeAluno = recebeNome.getText();
        
        double nota1 = Double.parseDouble(recebeNota1.getText());
        double nota2 = Double.parseDouble(recebeNota2.getText());
        if (!recebeNota1.getText().isEmpty() || !recebeNota2.getText().isEmpty()){
            notaFinal = (nota1+nota2)/2;
        }
        int faltas = Integer.parseInt(recebeFaltas.getText());

        try {
            alunoDAO.editarNotas(codigoAluno,codigoTurma, nota1, nota2,notaFinal, faltas);
        } catch (SQLException ex) {
            Logger.getLogger(EditarNotasGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Alteração bem sucedida!");
        dispose();
    }//GEN-LAST:event_btnSalvarNotasActionPerformed

    private void botao_cancelarDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cancelarDisciplinaActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_botao_cancelarDisciplinaActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formComponentShown

    private void recebeNota2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recebeNota2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recebeNota2ActionPerformed

    private void recebeNotaFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recebeNotaFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recebeNotaFinalActionPerformed

    private void recebeFaltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recebeFaltasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recebeFaltasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarNotasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarNotasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarNotasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarNotasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarNotasGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_cancelarDisciplina;
    private javax.swing.JButton btnSalvarNotas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField recebeCodigo;
    private javax.swing.JTextField recebeFaltas;
    private javax.swing.JTextField recebeNome;
    private javax.swing.JTextField recebeNota1;
    private javax.swing.JTextField recebeNota2;
    private javax.swing.JTextField recebeNotaFinal;
    private javax.swing.JTextField text_codTurma;
    // End of variables declaration//GEN-END:variables
}
